### ISSUE TITLE
Which zstd does it use?

### ISSUE THREAD

**Issue by martinheidegger** [zwb-ict/node-zstd#4]
It would be awesome to know against which version of which zstd is used?

**Comment by zwb-ict** [comment]
@martinheidegger   Zstandard v1.0
Thank you for your reminding. I'll update README.

**Comment by zwb-ict** [comment]
@martinheidegger sorry, my home's network is too bad, i have to update some info tomorrow.

**Comment by zwb-ict** [comment]
@martinheidegger done
